name: Terraform Automation

on:
  workflow_dispatch:
    inputs:
      repo_branch:
        description: 'Branch of the repository'
        required: true
        default: 'main'
      employeeId:
        description: 'Employee ID'
        required: true
      environment:
        description: 'Environment (DEV, STAGE, PROD)'
        required: true
        default: 'DEV'
      action:
        description: 'Action to perform (plan, apply, destroy)'
        required: true
        default: 'plan'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.repo_branch }}

      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.environment }}" = "PROD" ]; then
            echo "IC_API_KEY=${{ secrets.IC_API_KEY_PROD }}" >> $GITHUB_ENV
            echo "IAAS_CLASSIC_USERNAME=${{ secrets.IAAS_CLASSIC_USERNAME_PROD }}" >> $GITHUB_ENV
            echo "IAAS_CLASSIC_API_KEY=${{ secrets.IAAS_CLASSIC_API_KEY_PROD }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" = "STAGE" ]; then
            echo "IC_API_KEY=${{ secrets.IC_API_KEY_STAGE }}" >> $GITHUB_ENV
            echo "IAAS_CLASSIC_USERNAME=${{ secrets.IAAS_CLASSIC_USERNAME_STAGE }}" >> $GITHUB_ENV
            echo "IAAS_CLASSIC_API_KEY=${{ secrets.IAAS_CLASSIC_API_KEY_STAGE }}" >> $GITHUB_ENV
          else
            echo "IC_API_KEY=${{ secrets.IC_API_KEY_DEV }}" >> $GITHUB_ENV
            echo "IAAS_CLASSIC_USERNAME=${{ secrets.IAAS_CLASSIC_USERNAME_DEV }}" >> $GITHUB_ENV
            echo "IAAS_CLASSIC_API_KEY=${{ secrets.IAAS_CLASSIC_API_KEY_DEV }}" >> $GITHUB_ENV
          fi
    

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Adjust this version as needed

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: ${{ github.workspace }}/terraform/ibm/${{ github.event.inputs.environment }}
        run: |
          terraform init
          terraform plan -var="employee_id=${{ github.event.inputs.employeeId }}" -out=plan.tfplan

      - name: Print Terraform Plan (Aligned)
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: ${{ github.workspace }}/terraform/ibm/${{ github.event.inputs.environment }}
        run: |
          terraform show -no-color plan.tfplan | column -t
      

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ${{ github.workspace }}/terraform/ibm/${{ github.event.inputs.environment }}
        run: |
          terraform init
          terraform apply -auto-approve -var="employee_id=${{ github.event.inputs.employeeId }}"

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: ${{ github.workspace }}/terraform/ibm/${{ github.event.inputs.environment }}
        run: |
          terraform init
          terraform destroy -auto-approve -var="employee_id=${{ github.event.inputs.employeeId }}"
